theme: jekyll-theme-minimal
title: Boolector
description: A Satisfiability Modulo Theories (SMT) solver for the theories of fixed-size bit-vectors, arrays and uninterpreted functions.
google_analytics: UA-180012838-1
